steps:
  # Step to clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/jaiminbabariya7/dataproc-workflow-template.git']

  # Step to submit the Dataproc job
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        INPUT_GCS_PATH=gs://workflow_buckt/input_data/input.txt
        OUTPUT_BUCKET=gs://workflow_buckt/output_data/output.txt
        
        gcloud dataproc jobs submit pyspark dataproc-workflow-template/wordcount.py \
          --cluster=workflow-cluster \
          --region=northamerica-northeast2 \
          -- gs://workflow_buckt/input_data/input.txt gs://workflow_buckt/output_data/output.txt

options:
  logging: CLOUD_LOGGING_ONLY
