steps:
    
#- name: 'gcr.io/cloud-builders/gcloud'
  #args:
    #- 'dataproc'
    #- 'clusters'
    #- 'create'
    #- '${_CLUSTER_NAME}'
    #- '--region'
    #- 'northamerica-northeast2'
    #- '--single-node'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'dataproc'
    - 'jobs'
    - 'submit'
    - 'hadoop'
    #- '--cluster=${_CLUSTER_NAME}'  # Correct substitution format
    - '--cluster=workflow-cluster'
    - '--region=northamerica-northeast2'
    - '--class=org.apache.hadoop.examples.WordCount'
    - '--'
    - 'gs://workflow_bucket/input/input.txt'
    - 'gs://workflow_buckt/output_data/'

# Step 3: Delete the Dataproc cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataproc'
      - 'clusters'
      - 'delete'
      - 'workflow-cluster'
      - '--region=us-central1'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
