steps:
  # Step to clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/jaiminbabariya7/dataproc-workflow-template.git']

  # Step to submit the Dataproc job
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        INPUT_BUCKET=$_INPUT_BUCKET
        INPUT_PATH=input.txt
        OUTPUT_BUCKET=$_INPUT_BUCKET
        OUTPUT_PATH=output.txt
        
        gcloud dataproc jobs submit pyspark dataproc-workflow-template/wordcount.py \
          --cluster=workflow-cluster \
          --region=northamerica-northeast2 \
          -- gs://${INPUT_BUCKET}/${INPUT_PATH} gs://${OUTPUT_BUCKET}/${OUTPUT_PATH}
    substitutions:
    _INPUT_BUCKET: workflow_buckt

options:
  logging: CLOUD_LOGGING_ONLY
