steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--depth=1', 'https://github.com/jaiminbabariya7/dataproc-worflow-template.git', 'src']
- name: 'gcr.io/cloud-builders/java'
  args: ['javac', 'src/WordCount.java']
- name: 'gcr.io/cloud-builders/java'
  args: ['jar', 'cf', 'src/wc.jar', '-C', 'src', '.']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'src/wc.jar', 'gs://workflow_bucket/wc.jar']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'dataproc'
    - 'jobs'
    - 'submit'
    - 'hadoop'
    - '--cluster=workflow-cluster'
    - '--region=northamerica-northeast2'
    - '--jar=gs://workflow_bucket/wc.jar'
    - '--'
    - 'gs://workflow_bucket/input_data'
    - 'gs://workflow_bucket/output_data'

substitutions:
  _GITHUB_USERNAME: 'jaiminbabariya7'
  _REPO_NAME: 'dataproc-workflow-template'

trigger:
  github:
    owner: $_GITHUB_USERNAME
    name: $_REPO_NAME
    push:
      branch: '^main$'
